Algoritmo "matematoica"

Var
n1: real
n2: real
soma, sub, multi, divi: real




Inicio
escreva("Digite primeiro numero: ")
leia(n1)
escreval("o valor do n1 é: ", n1)
escreva("Digita segundo numero: ")
leia(n2)
escreval(" o valor do n2 é: ", n2)
soma <- (n1+n2)
sub <- (n1-n2)
multi <- (n1*n2)
divi <- (n1 / n2)
escreval("a media da soma é", soma)
escreval(" resultado da subtração é", sub)
escreval(" resultado da multiplicação é", multi)
escreval("resultado da divisão é", divi)


Fimalgoritmo