Algoritmo "exer1"

Var

correntista: caractere
agencia: real
conta: real


Inicio

escreval(" Qual nome do correntista? ")
leia(correntista)

escreval(" Qual sua agencia? ")
leia(agencia)

escreval("Qual sua conta? ")
leia(conta)

escreval("----------------")
escreval("---------------- ")
escreval("Segue seus dados: ")
escreval("Corretista: ", correntista )
escreval("Agencia ", agencia )
escreval("Conta: ", conta)


Fimalgoritmo