Algoritmo "exer5"

Var
reais, euro, conversao: real

Inicio
escreval("Digite seu valor em reais ? ")
leia(reais)

escreval("Digite quanto que é o valor euro hoje em dia? ")
leia(euro)

conversao <- reais * euro

escreval(" -------------------------")
escreval(" Conversão de reais para euro ")
escreval(" Valor em reais:" , reais)
escreval("Valor em euro: ", euro)
escreval(" -------------------------")
escreval("Resultado da conversão de reais para euro é:  ", conversao, " euros")


Fimalgoritmo